name: Monitor IPP

on:
  schedule:
    - cron: '*/20 * * * *'
  workflow_dispatch:

jobs:
  monitor:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
          python-version: '3.11'
      - run: pip install requests
      - run: python monitor_ipp.py
        timeout-minutes: 5
